version: '3'

networks:
  modvets_forms:

services:
#  nginx:
#    image: nginx:stable-alpine
#    container_name: modvets_nginx
#    ports:
#      - '8080:80'
#    networks:
#      modvets_forms:

  pgsql:
    image: postgres
    container_name: modvets_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: modvets_forms
    volumes:
      - ./docker/pgsql/data:/var/lib/postgresql/data
      - ./docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
    networks:
      modvets_forms:

#  redis:
#    image: redis
#    container_name: modvets_redis
#    restart: always
#    ports:
#      - '6379:6379'
#    networks:
#      modvets_forms:
